### PR TITLE
Feature/506 nystroem pcg

### LINKED ISSUE #506: Pre-conditioned block conjugate gradient method
Add functionality to `CgInfluence` to use a pre-conditioner and solve for several right-hand sights at the same time (block cg)

For the pre-conditioning, see: [Randomized Nyström Preconditioning, Z. Frangella et.al.](http://arxiv.org/abs/2110.02820)

For the stabilized block cg, see: [A breakdown-free block conjugate gradient method](http://link.springer.com/10.1007/s10543-016-0631-z)

### PR DESCRIPTION
**Pull request by schroedk**
### Description

This PR closes #506 

### Changes

- Add block variant of conjugate gradient
- Add preconditioning to cg

### Checklist

- [x] Wrote Unit tests (if necessary)
- [x] Updated Documentation (if necessary)
- [x] Updated Changelog
- [x] If notebooks were added/changed, added boilerplate cells are tagged with `"tags": ["hide"]` or `"tags": ["hide-input"]`

### CODE REVIEW

**Comment by schroedk** [comment]
Blocked by #511

**Comment by mdbenito** [comment]
> Blocked by #511

Merged

**Comment by schroedk** [comment]
> > Blocked by #511
> 
> Merged

@mdbenito, thanks, I updated the documentation to include the references to pre-conditioning and block cg variant

**Comment by schroedk** [comment]
@mdbenito finally I included the points from our review session, do you would like to have a look again? Otherwise I would merge it.

**Review by mdbenito — APPROVED** [review]

**Pull request merged**
